### ISSUE TITLE
package review

### ISSUE THREAD

**Issue by margauxgo** [openwashdata/wsabrazil#1]
Hi @larnsce @mianzg could one of you please review this package?

**Comment by larnsce** [comment]
Thanks, @margauxgo. I will take that over.

**Comment by larnsce** [comment]
I already had a brief look. You have been very quick with this package, well done. 

One item I noticed, which I suggest you rework is your data import and then the separation of columns in your `data_processing.R:

https://github.com/openwashdata/wsabrazil/blob/3aff4e2a70a8c5f872d3e62e2107d8adb29700e8/data-raw/data_processing.R#L11

You have a semicolon `;` separated file here. You can use `read_csv2()` or `read_delim(delim = ";")` to read the file properly. Then you don't need to separate the columns.

**Comment by margauxgo** [comment]
Thanks @larnsce, I just modified that.

Concerning the data format, I am still debating wether to pivot the dataset to long format to group the variables piped_water, well_spring_water, stored_rainwater and other_water_source into a variable named water_supply, the variables bathroom_sewerage, bathroom_septic_tank and bathroom_cesspit into a variable named sanitation and the variables bathroom_ditch, bathroom_waterbodies and bathroom_other into a variable named wastewater, or to keep it in wide format.

For now, I illustrated how to pivot it for simpler analysis in the example and kept it in wide format otherwise.

What do you think?

**Comment by mianzg** [comment]
> Thanks @larnsce, I just modified that.
> 
> Concerning the data format, I am still debating wether to pivot the dataset to long format to group the variables piped_water, well_spring_water, stored_rainwater and other_water_source into a variable named water_supply, the variables bathroom_sewerage, bathroom_septic_tank and bathroom_cesspit into a variable named sanitation and the variables bathroom_ditch, bathroom_waterbodies and bathroom_other into a variable named wastewater, or to keep it in wide format.
> 
> For now, I illustrated how to pivot it for simpler analysis in the example and kept it in wide format otherwise.
> 
> What do you think?

I also had a similar debate: https://github.com/openwashdata/whatawaste/issues/2

I would for now keep it in wide format for now.

**Comment by mianzg** [comment]
1. Please refine the 1st figure with more information, e.g. title, x/y-axis label 
2. What is the `references` directory?
